# Azure App Service deployment workflow
name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_API: 'bernard-portfolio-api'
  AZURE_WEBAPP_NAME_WEB: 'bernard-portfolio-web'
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Build API
      run: dotnet build src/Portfolio.Api/Portfolio.Api.csproj --configuration Release
    
    - name: Publish API
      run: dotnet publish src/Portfolio.Api/Portfolio.Api.csproj -c Release -o ./api-publish
    
    - name: Deploy API to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: ./api-publish

  build-and-deploy-web:
    runs-on: ubuntu-latest
    needs: build-and-deploy-api
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Build Web
      run: dotnet build src/Portfolio.Web/Portfolio.Web.csproj --configuration Release
    
    - name: Publish Web
      run: dotnet publish src/Portfolio.Web/Portfolio.Web.csproj -c Release -o ./web-publish
    
    - name: Deploy Web to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "./web-publish/wwwroot"
        output_location: ""