# Show Repository Status - What's tracked vs ignored
Write-Host "📊 Portfolio Repository Status" -ForegroundColor Cyan
Write-Host "================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "🔍 Important Files (Tracked):" -ForegroundColor Green
Write-Host "  📁 Source Code:"
Write-Host "    - src/ (All source code)"
Write-Host "    - Portfolio.sln"
Write-Host ""
Write-Host "  📋 Documentation:"
Write-Host "    - README.md"
Write-Host "    - DEPLOYMENT_GUIDE.md"
Write-Host "    - EMAIL_SETUP_INSTRUCTIONS.md"
Write-Host ""
Write-Host "  🚀 Deployment:"
Write-Host "    - docker-compose.yml"
Write-Host "    - azure-deploy.yml"
Write-Host "    - .env.example"
Write-Host "    - Dockerfiles"
Write-Host ""
Write-Host "  🔧 Scripts:"
Write-Host "    - deploy.ps1"
Write-Host "    - build.ps1"
Write-Host "    - run-dev.ps1"
Write-Host "    - portfolio-status.ps1"

Write-Host ""
Write-Host "🚫 Ignored Files (Not Tracked):" -ForegroundColor Red
Write-Host "  🗂️ Build Output:"
Write-Host "    - bin/, obj/, publish/"
Write-Host "    - Debug/, Release/"
Write-Host ""
Write-Host "  🔐 Sensitive:"
Write-Host "    - .env (actual environment variables)"
Write-Host "    - *.log files"
Write-Host "    - Certificate files"
Write-Host ""
Write-Host "  📝 Temporary Documentation:"
Write-Host "    - *_SUMMARY.md"
Write-Host "    - *_IMPLEMENTATION.md"
Write-Host "    - *_STATUS.md"
Write-Host "    - Development notes"
Write-Host ""
Write-Host "  🧪 Test Files:"
Write-Host "    - test-*.ps1"
Write-Host "    - cleanup-*.ps1"
Write-Host ""
Write-Host "  💻 IDE Files:"
Write-Host "    - .vs/, .vscode/"
Write-Host "    - *.user, *.suo"

Write-Host ""
Write-Host "📈 Repository Size Optimization:" -ForegroundColor Yellow
Write-Host "  ✅ Ignoring build artifacts saves ~50-100MB"
Write-Host "  ✅ Ignoring logs and temp files saves ~10-20MB"
Write-Host "  ✅ Ignoring IDE files saves ~5-10MB"
Write-Host "  ✅ Clean, focused repository for deployment"

Write-Host ""
Write-Host "🎯 Next Steps:" -ForegroundColor Cyan
Write-Host "  1. Run: git add ."
Write-Host "  2. Run: git commit -m 'Portfolio ready for deployment'"
Write-Host "  3. Run: git push"
Write-Host "  4. Deploy using: ./deploy.ps1"